/* tslint:disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    uploads: Upload;
    pages: Page;
    posts: Post;
    relations: Relation;
    users: User;
  };
  globals: {};
}
export interface Upload {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Page {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
export interface Post {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
export interface Relation {
  id: string;
  hasOne?: string | Post;
  hasOnePoly?:
    | {
        value: string | Page;
        relationTo: 'pages';
      }
    | {
        value: string | Post;
        relationTo: 'posts';
      };
  hasMany?: string[] | Post[];
  hasManyPoly?:
    | (
        | {
            value: string;
            relationTo: 'pages';
          }
        | {
            value: string;
            relationTo: 'posts';
          }
      )[]
    | (
        | {
            value: Page;
            relationTo: 'pages';
          }
        | {
            value: Post;
            relationTo: 'posts';
          }
      )[];
  upload?: string | Upload;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
